apiVersion: apps/v1
kind: Deployment
metadata:
  name: myblog
spec:
  selector:
    matchLabels:
      app: myblog
  replicas: 1
  template:
    metadata:
      labels:
        app: myblog
    spec:
      containers:
      - name: myblog
        image: kennethfaria/myblog
        ports:
        - containerPort: 3000
        env:
          - name: MONGODB_URI
            value: 'mymongo-service:27017'
          - name: SECRET
            value: 'shhhhhh'
